### ISSUE TITLE
oneDAL identified lead maintainers

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#10]
- Publish the names of the lead maintainers and reviewers for contributions to the project.
- Identified way to contact lead maintainers of the project published on the project README

Acceptance Criteria:
- The README or CONTRIBUTOR file lists the lead maintainers
- The README or CONTRIBUTOR file lists how to contact the project maintainers

**Comment by napetrov** [comment]
there was already email for contacting maintainers. Project using codeowners for corresponding blocks of the code 
https://github.com/oneapi-src/oneDAL/pull/2822 - also points to non Intel contacts and link things together
