### ISSUE TITLE
oneTBB Publish list of maintainers

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#100]
- Publish a list of the lead maintainers and reviewers for contributions to the project (minimum GitHub usernames).

Acceptance Criteria:

- The README or CONTRIBUTOR file lists the lead maintainers

**Comment by pavelkumbrasev** [comment]
The maintainers file is merged:
https://github.com/oneapi-src/oneTBB/commit/c4ec31c23736301d63fb64a55d21fa2e44cfb570
