### ISSUE TITLE
Add contact for maintainers that is not Intel specific

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#101]
The contact for the project is an Intel domain email address.
In the interest of the project being openly governed use an alternative communication channel.
This could be a mailing list or dedicated UXL email address. Contact operations@uxlfoundation.org to set up an email address

**Comment by vbm23** [comment]
@pavelkumbrasev Did you manage to contact [operations@uxlfoundation.org](mailto:operations@uxlfoundation.org) to set up an email address as an an alternative communication channel or dedicated UXL email address in interest of project being openly governed ?

**Comment by vbm23** [comment]
@pavelkumbrasev No worries, based on your convivence you can take some time to do that as we still have a month more to go when it gets due

**Comment by pavelkumbrasev** [comment]
Team agreed to remove email list from the README because public communication channels are defined in the project README.
https://github.com/oneapi-src/oneTBB/pull/1509

**Comment by vbm23** [comment]
https://github.com/oneapi-src/oneTBB/pull/1509 Merged
