### ISSUE TITLE
oneTBB Enable Open SSF Scorecard GitHub Badge

### ISSUE THREAD

**Issue by rozhukov** [uxlfoundation/open-source-working-group#106]
Enable OpenSSF Scorecard badge for your repo:
https://github.com/ossf/scorecard?tab=readme-ov-file#scorecard-badges

Example: https://github.com/OpenVisualCloud/Media-Transport-Library

**Comment by rozhukov** [comment]
Done. Thanks team!
https://github.com/oneapi-src/oneTBB

**Comment by omalyshe** [comment]
Also added the workflow - https://github.com/oneapi-src/oneTBB/actions/workflows/ossf-scorecard.yml
