### ISSUE TITLE
oneDAL Enable Open SSF Scorecard GitHub Badge

### ISSUE THREAD

**Issue by rozhukov** [uxlfoundation/open-source-working-group#108]
Enable OpenSSF Scorecard badge for your repo:
https://github.com/ossf/scorecard?tab=readme-ov-file#scorecard-badges

Example: https://github.com/OpenVisualCloud/Media-Transport-Library

**Comment by napetrov** [comment]
Added in https://github.com/oneapi-src/oneDAL/pull/2838  @rozhukov  - please review
