### ISSUE TITLE
oneDPL identified lead maintainers

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#11]
- Publish the names of the lead maintainers and reviewers for contributions to the project.
- Identified way to contact lead maintainers of the project published on the project README

Acceptance Criteria:
- The README or CONTRIBUTOR file lists the lead maintainers
- The README or CONTRIBUTOR file lists how to contact the project maintainers

**Comment by vbm23** [comment]
@timmiesmith The table of maintainers to be provided as a separate PR based on comment https://github.com/oneapi-src/oneDPL/pull/1635/files#r1651231325

**Comment by vbm23** [comment]
oneDPL team previously requested additional time for reviews and awaiting 1 review approval

**Comment by timmiesmith** [comment]
The PR has been merged.
