### ISSUE TITLE
oneDNN documented processes for leadership

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#12]
The project shall publish a process for how roles are appointed within the project. The CNCF has a [template for this process](https://github.com/cncf/project-template/blob/main/GOVERNANCE-maintainer.md) that should be used as a best practice guide. The UXL Foundation Open Source Working Group shall agree on the processes set by each project.

Acceptance Criteria:
- A set of processes and guidelines have been published on the project repository describing what the roles are within the project and how they are appointed

**Comment by vpirogov** [comment]
Leadership process is published in [MAINTAINERS.md](https://github.com/oneapi-src/oneDNN/blob/main/MAINTAINERS.md).
