### ISSUE TITLE
oneDPL documented processes for leadership

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#15]
The project shall publish a process for how roles are appointed within the project. The CNCF has a [template for this process](https://github.com/cncf/project-template/blob/main/GOVERNANCE-maintainer.md) that should be used as a best practice guide. The UXL Foundation Open Source Working Group shall agree on the processes set by each project.

Acceptance Criteria:
- A set of processes and guidelines have been published on the project repository describing what the roles are within the project and how they are appointed

**Comment by vbm23** [comment]
@timmiesmith this ticket would be related to https://github.com/uxlfoundation/open-source-working-group/issues/21

**Comment by vbm23** [comment]
@timmiesmith mentioned that he has a draft & hope to have up for review last week

**Comment by vbm23** [comment]
@timmiesmith Would you have any updates with regards to this ticket as I assume you have been discussing with Pavel sometime last week?

**Comment by timmiesmith** [comment]
@vbm23 https://github.com/oneapi-src/oneDPL/pull/1940 has been submitted for this.  We define the process for advancing from Contributor to Code Owner to Maintainer within oneDPL as well as leaving a role.

**Comment by timmiesmith** [comment]
https://github.com/oneapi-src/oneDPL/pull/1940 has been merged
