### ISSUE TITLE
OCK UXL Foundation Identity

### ISSUE THREAD

**Issue by vbm23** [uxlfoundation/open-source-working-group#153]
**"Project pages with the UXL Foundation links, Logo and Identity**

**Checkpoint Description / Activity**
1) Update project icon with UXL Foundation Logo to replace oneAPI logo unless project has its own Logo
2) Update ""About"" Section for 
    a) Link to UXL foundation org https://github.com/uxlfoundation
    b) Include UXL Foundation logo at top of README
    c) Specify Project is part of the UXL Foundation http://www.uxlfoundation.org
    d) Specify Project is implementation of the oneAPI specification __ component https://spec.oneapi.io/
3) Add ""Governance"" Section
   a) Describe governance by UXL Foundation
   b) Capture mailing lists
   c) Point to CONTRIBUTING Page for more information"

**Model Project References**
1) https://github.com/oneapi-src/oneDNN
2) https://github.com/oneapi-src/oneDNN/commit/0b24bda7e8de8c6bd65548d25a2619cffa7d7e37"

**Comment by uwedolinsky** [comment]
https://github.com/uxlfoundation/oneapi-construction-kit/pull/606 is merged
