### ISSUE TITLE
oneCCL documented process for leadership

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#16]
The project shall publish a process for how roles are appointed within the project. The CNCF has a [template for this process](https://github.com/cncf/project-template/blob/main/GOVERNANCE-maintainer.md) that should be used as a best practice guide. The UXL Foundation Open Source Working Group shall agree on the processes set by each project.

Acceptance Criteria:
- A set of processes and guidelines have been published on the project repository describing what the roles are within the project and how they are appointed

**Comment by vbm23** [comment]
@Maria1Petrova here task would be to identify various Project Role Names, its Responsibilities, its Privileges and Process of taking up that Role in the project and you can refer [other project](https://github.com/oneapi-src/oneDNN/blob/main/MAINTAINERS.md) if not already done

**Comment by Maria1Petrova** [comment]
Hi @vbm23 , is this information https://github.com/oneapi-src/oneCCL/blob/master/MAINTAINERS.md enough or do we need to add anything else?

**Comment by vbm23** [comment]
@Maria1Petrova This should be a good starting point and incase changes are needed we can update/discuss as required
