### ISSUE TITLE
oneDNN identified roles for contributors

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#17]
The project will publish identified roles for contributors, including maintainers/reviewers for specific backends alongside project lead maintainers/reviewers. The [CNCF community ladder](https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md) can be used as a guide.

Acceptance Criteria:
- A list of roles and responsibilities is available to read on the project repository
- It is clear for the community what roles are available to them and how they can attain them

**Comment by vpirogov** [comment]
Contributor roles are defined in [MAINTAINERS.md](https://github.com/oneapi-src/oneDNN/blob/main/MAINTAINERS.md).
