### ISSUE TITLE
oneMKL identified roles for contributors

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#18]
The project will publish identified roles for contributors, including maintainers/reviewers for specific backends alongside project lead maintainers/reviewers. The [CNCF community ladder](https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md) can be used as a guide.

Acceptance Criteria:
- A list of roles and responsibilities is available to read on the project repository
- It is clear for the community what roles are available to them and how they can attain them

**Comment by vbm23** [comment]
@mkrainiuk Did the team manage to describe list of roles, responsibilities, what roles are available and how they can attain them?

**Comment by mkrainiuk** [comment]
> @mkrainiuk Did the team manage to describe list of roles, responsibilities, what roles are available and how they can attain them?

We plan to do it in the next few weeks.
