### ISSUE TITLE
oneMKL documented process for leadership roles

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#19]
The project shall publish a process for how roles are appointed within the project. The CNCF has a [template for this process](https://github.com/cncf/project-template/blob/main/GOVERNANCE-maintainer.md) that should be used as a best practice guide. The UXL Foundation Open Source Working Group shall agree on the processes set by each project.

Acceptance Criteria:
- A set of processes and guidelines have been published on the project repository describing what the roles are within the project and how they are appointed

**Comment by vbm23** [comment]
@mkrainiuk 1 Approval pending for MR
