### ISSUE TITLE
oneDAL identified roles for contributors

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#20]
The project will publish identified roles for contributors, including maintainers/reviewers for specific backends alongside project lead maintainers/reviewers. The [CNCF community ladder](https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md) can be used as a guide.

Acceptance Criteria:
- A list of roles and responsibilities is available to read on the project repository
- It is clear for the community what roles are available to them and how they can attain them

**Comment by vbm23** [comment]
@napetrov The first part of the ref doc [here](https://github.com/oneapi-src/oneDNN/blob/main/MAINTAINERS.md) provides the approach towards Role Name, its Responsibilities, its Privileges and Process of taking up that Role in the project.

Let me know your views

**Comment by vbm23** [comment]
@napetrov Did the team manage to describe list of roles, responsibilities, what roles are available and how they can attain them?

**Comment by vbm23** [comment]
Pull Request https://github.com/oneapi-src/oneDAL/pull/2909

**Comment by vbm23** [comment]
@napetrov Is the above PR related to this ticket?

**Comment by vbm23** [comment]
@napetrov Noted and pushed to "To Do" from "In Progress"

**Comment by napetrov** [comment]
here is PR - https://github.com/oneapi-src/oneDAL/pull/2916

**Comment by vbm23** [comment]
https://github.com/oneapi-src/oneDAL/pull/2916 merged
