### ISSUE TITLE
oneDPL Identified roles for contributors

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#21]
The project will publish identified roles for contributors, including maintainers/reviewers for specific backends alongside project lead maintainers/reviewers. The [CNCF community ladder](https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md) can be used as a guide.

Acceptance Criteria:
- A list of roles and responsibilities is available to read on the project repository
- It is clear for the community what roles are available to them and how they can attain them

**Comment by vbm23** [comment]
@timmiesmith The first part of the ref doc [here](https://github.com/oneapi-src/oneDNN/blob/main/MAINTAINERS.md) provides the approach towards Role Name, its Responsibilities, its Privileges and Process of taking up that Role in the project.

Let me know your views

**Comment by vbm23** [comment]
@timmiesmith Did the team manage to describe list of roles, responsibilities, what roles are available and how they can attain them?

**Comment by vbm23** [comment]
@timmiesmith Do we have any progress to report for this ticket, if so then the PR link would be useful.

**Comment by vbm23** [comment]
@timmiesmith mentioned that he has a draft & hope to have up for review this week

**Comment by vbm23** [comment]
@timmiesmith Would you have any updates with regards to this ticket as I assume you have been discussing with Pavel sometime last week?

**Comment by timmiesmith** [comment]
@vbm23 https://github.com/oneapi-src/oneDPL/pull/1940 has been submitted to define the project roles and the responsibilities and privileges of each.

**Comment by timmiesmith** [comment]
https://github.com/oneapi-src/oneDPL/pull/1940 has been merged.
