### ISSUE TITLE
oneCCL identified roles for contributors

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#22]
The project will publish identified roles for contributors, including maintainers/reviewers for specific backends alongside project lead maintainers/reviewers. The [CNCF community ladder](https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md) can be used as a guide.

Acceptance Criteria:
- A list of roles and responsibilities is available to read on the project repository
- It is clear for the community what roles are available to them and how they can attain them

**Comment by vbm23** [comment]
@Maria1Petrova The first part of the ref doc [here](https://github.com/oneapi-src/oneDNN/blob/main/MAINTAINERS.md) provides the approach towards Role Name, its Responsibilities, its Privileges and Process of taking up that Role in the project.

Let me know your views

**Comment by vbm23** [comment]
@Maria1Petrova Did the team manage to describe list of roles, responsibilities, what roles are available and how they can attain them?

**Comment by vbm23** [comment]
@Maria1Petrova Do we have any progress to report for this ticket, if so then the PR link would be useful.

**Comment by Maria1Petrova** [comment]
Hi @vbm23 , yes, we have an internal PR and it is going through a review within the team

**Comment by maciekpac** [comment]
Hi @vbm23 ,

we have merged the internal PR, ported it to opensource and merged:

https://github.com/oneapi-src/oneCCL/pull/140

Please let us know if anything more is required.

**Comment by vbm23** [comment]
Thanks @maciekpac, can now close the ticket
