### ISSUE TITLE
oneMKL help wanted or wish list for contributors

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#25]
Publish a set of tasks, issues or features that could be implemented and contributed to the project. These can be in the issue tracker using the "help wanted" label. The Slack channel, SIG or other groups could be used to seek out specific gaps and these can include documentation, build, CI, test as well as implementation work.

Acceptance Criteria:
- There are a good number of issues that have the "help wanted" label in the project

**Comment by vbm23** [comment]
@mkrainiuk was trying to check if can find any issues marked with "Help Wanted" Label in your project through below link but unable for now
https://github.com/oneapi-src/oneMKL/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Comment by mkrainiuk** [comment]
Hi @vbm23 we didn't have this tag yet, I've just added it to the project.

**Comment by vbm23** [comment]
@mkrainiuk Not sure, if we can have some issues with the label, perhaps one might need to check the open issues and apply the label where relevant.

**Comment by mkrainiuk** [comment]
I've added new tag where it's applicable to the existing oneMKL issues/features https://github.com/oneapi-src/oneMKL/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22 

@vbm23 please let me know if this list is sufficient as the stating point for this task.

**Comment by vbm23** [comment]
@mkrainiuk Yes, this would be the right approach and can close this ticket
