### ISSUE TITLE
oneDAL help wanted or wish list for contributions

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#26]
Publish a set of tasks, issues or features that could be implemented and contributed to the project. These can be in the issue tracker using the "help wanted" label. The Slack channel, SIG or other groups could be used to seek out specific gaps and these can include documentation, build, CI, test as well as implementation work.

Acceptance Criteria:
- There are a good number of issues that have the "help wanted" label in the project

**Comment by napetrov** [comment]
Already exist for oneDAL - https://github.com/oneapi-src/oneDAL/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
