### ISSUE TITLE
oneMKL identified way to contact maintainers

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#29]
The README or CONTRIBUTOR file should list how to get in touch with the maintainers of the project. This should preferably be using a method that can include any individual rather than linked to a specific organisation and could be an email group/alias or the Slack channel.

Definition of done:
- There is a published way to contact the maintainers of the project

**Comment by mkrainiuk** [comment]
We plan to create new github teams for better way to contact maintainers and reps for each domain. I will update the documentation when teams will be created.

**Comment by mkrainiuk** [comment]
Links were fixed in https://github.com/oneapi-src/oneMKL/pull/520
