### ISSUE TITLE
oneDAL identified way to contact maintainers

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#30]
The README or CONTRIBUTOR file should list how to get in touch with the maintainers of the project. This should preferably be using a method that can include any individual rather than linked to a specific organisation and could be an email group/alias or the Slack channel.

Definition of done:
- There is a published way to contact the maintainers of the project

**Comment by napetrov** [comment]
Already was defined in docs but adding additional touches - https://github.com/oneapi-src/oneDAL/pull/2822
