### ISSUE TITLE
oneDPL identified way to contact lead maintainers

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#31]
The README or CONTRIBUTOR file should list how to get in touch with the maintainers of the project. This should preferably be using a method that can include any individual rather than linked to a specific organisation and could be an email group/alias or the Slack channel.

Definition of done:
- There is a published way to contact the maintainers of the project

**Comment by timmiesmith** [comment]
README is updated to note availability of Slack channel to contact developers.
