### ISSUE TITLE
oneDPL project makes and records decisions in public

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#35]
Publish and follow a process for RFCs to ensure that the community has the opportunity to comment and contribute to changes, features and other proposals for the project. 
The oneDNN project implements a RFC process that has been operating for a while and can be used as a template or guide.

Acceptance Criteria:
- A process has been reviewed by the team and published on the project repo describing the process for RFCs
- The process is being used by the oneDPL project team

**Comment by akukanov** [comment]
PR review: https://github.com/oneapi-src/oneDPL/pull/1878
