### ISSUE TITLE
oneMKL build instruction improvements

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#38]
The build instructions for oneMKL could be clearer, in particular for the Nvidia and AMD backends but also for using an open source backend such as portBLAS.
It would benefit the community if there was clearer information on the project README on how to build the project from source and link to different back end libraries. For example [this PR](https://github.com/oneapi-src/oneMKL/pull/458) outlines one of the improvements.

Acceptance Criteria:
- Clear instructions for anyone to compile oneMKL from source with any of the available backends
- Instructions have been reviewed by community members

**Comment by Rbiessy** [comment]
Note that we also started an open issue in https://github.com/oneapi-src/oneMKL/issues/459
We will probably start this work ourselves when we have the time but other contributions are more than welcome!

**Comment by vbm23** [comment]
https://github.com/oneapi-src/oneMKL/pull/510 opened and waiting for 2nd review approval

**Comment by vbm23** [comment]
https://github.com/oneapi-src/oneMKL/pull/510#event-13226021709 Merged
https://github.com/oneapi-src/oneMKL/pull/490 Merged

**Comment by vbm23** [comment]
@mkrainiuk Based on the above 2 MRs, would you consider this meets the acceptance criteria for this issue?

**Comment by mkrainiuk** [comment]
Yes, I think it was great improvement for the build instructions. I will close the task.
