### ISSUE TITLE
oneMKL Quick start documentation

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#39]
Write a quick start guide for the project that explains clearly a user's options for the library and what it provides. An example of the sections for this guide would be:

Introduction
How to install/build including options available
A simple example of an API call

**Comment by mkrainiuk** [comment]
> A simple example of an API call

Does the example from [README](https://github.com/oneapi-src/oneMKL?tab=readme-ov-file#host-api) cover this requirement?

**Comment by vbm23** [comment]
@mkrainiuk merged through https://github.com/oneapi-src/oneMKL/pull/510, hence will close this issue
