### ISSUE TITLE
oneMKL use of Slack channel

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#4]
- Link to the UXL Foundation Slack workspace and channel from the project README
- Assign team member(s) to monitor the Slack channel
- Set up notifications in the oneMKL Slack channel when new RFCs are added to the project repo for community review and comment

Acceptance Criteria:
- Link to Slack available on README
- Named team member(s) monitoring channel
- Notifications appearing on the Slack channel when new RFCs are added to the project

**Comment by sknepper** [comment]
@rodburns - Looking at the free vs paid Slack plans here: https://slack.com/pricing/paid-vs-free , it appears that people on the free plan see only a 90 day history of conversations.
Will the use of Slack for certain discussions/decisions cause the history to be hidden to users who are using a free Slack plan? In that case, it seems like keeping the main discussions on the Github project itself would be more appropriate.
If this concern should be raised elsewhere, please move the discussion there. Thanks!

**Comment by rodburns** [comment]
The general guidance would be that decision making is made on the GitHub repo itself rather than in Slack. That is more transparent in any case. But general discussions on things can be had on Slack where conversations and threads are easier to have than on GitHub. This way losing old conversations shouldn't matter too much, but if it is a problem we can talk about how to solve that.

**Comment by vbm23** [comment]
https://github.com/oneapi-src/oneMKL/pull/481 created by @rscohn2

**Comment by vbm23** [comment]
Awaiting https://github.com/oneapi-src/oneMKL/pull/481 to be merged by @vpirogov / @mkrainiuk post 2 approvals

**Comment by vbm23** [comment]
@sknepper @mkrainiuk Kindly help notify when the slack token as a secret for the repo is worked out from [PR](https://github.com/oneapi-src/oneMKL/pull/481) by Alexey.

In order to meet the other acceptance criterias, can one help update links to UXL Foundation Slack Workspace and [oneMKL channel](https://app.slack.com/client/T06EGKQ30NM/C06HPEQ1BRS) in [Contributing Guidelines](https://github.com/oneapi-src/oneMKL/blob/develop/CONTRIBUTING.md) and if applicable also to Support section of README.

So also Team members involved into working with external contributors would need to monitor the channel.

**Comment by mkrainiuk** [comment]
"Named team member(s) monitoring channel" will be covered by https://github.com/uxlfoundation/open-source-working-group/issues/8 when we define the list of maintainers.

**Comment by vbm23** [comment]
The secret has been created by Alexey & @rscohn2 confirmed that it works [here](https://github.com/oneapi-src/oneMKL/pull/481#issuecomment-2112878169)

**Comment by vbm23** [comment]
Named team member(s) monitoring channel to be taken up in https://github.com/uxlfoundation/open-source-working-group/issues/8

**Comment by mkrainiuk** [comment]
List of Intel team member monitoring channel was defined and approved. We are waiting for some reps from Codeplay as well.
