### ISSUE TITLE
oneDAL issue tracker templates

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#40]
Implement issue templates for the issue tracker on the GitHub project. 
The oneMKL project does this https://github.com/oneapi-src/oneMKL/issues/new/choose and can be used to help make the templates.

Acceptance Criteria:
- Templates have been added to the project

**Comment by vbm23** [comment]
@napetrov With reference for this you can refer to [oneTBB]([url](https://github.com/oneapi-src/oneTBB/pull/1400/files)) or even [oneDPL](https://github.com/oneapi-src/oneDPL/pull/1639/files) on how issue tracker templates can be created.

**Comment by vbm23** [comment]
@napetrov Team can help efine basic templates in your project such as "Ask a question", "Report a bug or a performance issue", "Request a feature" & "Request a documentation change"

**Comment by vbm23** [comment]
Pull Request https://github.com/oneapi-src/oneDAL/pull/2903

**Comment by napetrov** [comment]
Integrated
