### ISSUE TITLE
oneDAL Slack integration

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#42]
Integrate notifications with the oneDAL Slack channel for RFCs so that the community can see when new RFCs are available for comment and review.

Acceptance Criteria:
- Slack notifications are made on the oneDAL channel when new RFCs are published on the GitHub repo

**Comment by vbm23** [comment]
Updated from @rodburns to provide consistency among reported issues

- Link to the UXL Foundation Slack workspace and channel from the project README
- Assign team member(s) to monitor the Slack channel
- Set up notifications in the oneDAL Slack channel when new RFCs are added to the project repo for community review and comment

Acceptance Criteria:

- Link to Slack available on README
- Named team member(s) monitoring channel
- Notifications appearing on the Slack channel when new RFCs are added to the project

**Comment by vbm23** [comment]
Awaiting PR to be created by @rscohn2

**Comment by napetrov** [comment]
RFC notifications integration created - https://github.com/oneapi-src/oneDAL/pull/2778

**Comment by vbm23** [comment]
@napetrov In order to meet the other acceptance criterias, you can help update links to UXL Foundation Slack Workspace and [oneDAL channel](https://app.slack.com/client/T06EGKQ30NM/C06HPEU1ELU?selected_team_id=T06EGKQ30NM) in relevant sections of README.

So also assigning team members who would be involved into working with external contributors so as to monitor the channel.

**Comment by napetrov** [comment]
yes, we do have team members assigned. will update link to slack in upcoming PRs

**Comment by vbm23** [comment]
@napetrov Can you help share the required PRs so we can close this ticket if acceptance criteria's have been met.

**Comment by napetrov** [comment]
adding link to the slack in PR - https://github.com/oneapi-src/oneDAL/pull/2822
