### ISSUE TITLE
oneDAL installation process documented

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#43]
Instructions on the README should link to the different options available to developers, from downloading the binaries from the oneAPI Base Toolkit to building the project from source. This is especialy important now that the Arm target has been added.

Acceptance Criteria:
- Clear links from the README to the information on how to install oneDAL from both binaries and compiling from source.

**Comment by vbm23** [comment]
Installation reviewed and merged in https://github.com/oneapi-src/oneDAL/pull/2788
