### ISSUE TITLE
oneDPL remove contributor licensing agreement

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#44]
The requirement to [sign your work](https://github.com/oneapi-src/oneDPL/blob/main/CONTRIBUTING.md#sign-your-work) for the oneDPL project is inconsistent with the other projects in the UXL Foundation, and the LLVM compiler project for example. Since the project is covered by the Apache 2.0 license this step is not necessary. 
This issue tracks the removal of this step and requirement, as well as the associated mentions in the project documentation.

Acceptance Criteria:
- Developers are no longer required to sign their work when contributing to oneDPL

**Comment by timmiesmith** [comment]
PR is merged.
