### ISSUE TITLE
oneCCL remove contributor agreement

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#45]
The requirement to [sign your work](https://github.com/oneapi-src/oneDPL/blob/main/CONTRIBUTING.md#sign-your-work) for the oneCCL project is inconsistent with the other projects in the UXL Foundation, and the LLVM compiler project for example. Since the project is covered by the Apache 2.0 license this step is not necessary. 
This issue tracks the removal of this step and requirement, as well as the associated mentions in the project documentation.

Acceptance Criteria:
- Developers are no longer required to sign their work when contributing to oneCCL

**Comment by vbm23** [comment]
@Maria1Petrova You can refer to this oneDPL reference Tickethttps://github.com/uxlfoundation/open-source-working-group/issues/44

**Comment by Maria1Petrova** [comment]
@shirosankaku can you please create a pr to our innersource and open source repo with removing "signing off" step from CONTRIBUTING.md?

**Comment by Maria1Petrova** [comment]
https://github.com/oneapi-src/oneCCL/pull/128 is merged

**Comment by Maria1Petrova** [comment]
@vbm23 can we close this one?
