### ISSUE TITLE
oneDAL documented decision making process

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#46]
Define processes for decision making within the oneDAL project. This should include a RFC process for new design and feature proposals 
(see oneDNN for example - PR tagged RFC that links to the proposal on the GitHub wiki).

Acceptance Criteria:
Decision making process published in the repository and reviewed by the community

**Comment by vbm23** [comment]
@napetrov Projects have initiated describing the RFC Process with Template in their respective projects and would be nice if all projects can align in the naming convention and then can always continually improve to include things that do not fit right now
https://github.com/oneapi-src/oneCCL/tree/rfcs
https://github.com/oneapi-src/oneDNN/tree/rfcs

**Comment by napetrov** [comment]
@vbm23 - yes we will be using RFCs as well.  Will be populated with templates/readme and will start with decisions there 
https://github.com/oneapi-src/oneDAL/tree/rfcs

**Comment by vbm23** [comment]
@napetrov Thanks for the update and progressed the ticket for now

**Comment by napetrov** [comment]
https://github.com/oneapi-src/oneDAL/pull/2914

**Comment by vbm23** [comment]
https://github.com/oneapi-src/oneDAL/pull/2914 Merged
