### ISSUE TITLE
oneDAL implement a quality assurance process

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#48]
The [CONTRIBUTING](https://github.com/oneapi-src/oneDAL/blob/main/CONTRIBUTING.md) guide should explain, or link to documentation on how to run the required smoke tests or similar before submitting a PR to the project, and publishing these results with the PR if they are not on a public CI system.

Acceptance Criteria:
- There is clear documentation on how to run any relevant project wide tests required for contributions to the project and this is linked or included in the CONTRIBUTING page

**Comment by napetrov** [comment]
Process was defined in contributing section.  This PR also extends this to bazel testing and link Bazel guide for running them 
https://github.com/oneapi-src/oneDAL/pull/2822
