### ISSUE TITLE
oneDPL implements a quality assurance process

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#49]
The [CONTRIBUTING](https://github.com/oneapi-src/oneDPL/blob/main/CONTRIBUTING.md#how-to-contribute) guide should explain, or link to documentation on how to run the required smoke tests or similar before submitting a PR to the project, and publishing these results with the PR if they are not on a public CI system.

Acceptance Criteria:
- There is clear documentation on how to run any relevant project wide tests required for contributions to the project and this is linked or included in the CONTRIBUTING page

**Comment by vbm23** [comment]
@timmiesmith You can refer this ticket https://github.com/uxlfoundation/open-source-working-group/issues/58 for unit test guidelines and commands as a reference

**Comment by timmiesmith** [comment]
PR has been merged.
