### ISSUE TITLE
oneDNN use of Slack channel

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#5]
- Link to the UXL Foundation Slack workspace and channel from the project README
- Assign team member(s) to monitor the Slack channel
- Set up notifications in the oneDNN Slack channel when new RFCs are added to the project repo for community review and comment

Acceptance Criteria:

- Link to Slack available on README
- Named team member(s) monitoring channel
- Notifications appearing on the Slack channel when new RFCs are added to the project

**Comment by vpirogov** [comment]
Links to Slack included into [Support](https://github.com/oneapi-src/oneDNN#support) and [Contributing](https://github.com/oneapi-src/oneDNN#contributing) sections of README.

Team members involved into working with external contributors are monitoring the channel.

Would appreciate help with enabling notifications for new RFC. We are using `rfc` label to indicate these.

**Comment by rodburns** [comment]
Setting up the Slack notifications requires repo admin access I believe. Robert is helping to figure that out.

**Comment by rscohn2** [comment]
Addressed by https://github.com/oneapi-src/oneDNN/pull/1900
