### ISSUE TITLE
oneDPL Code of Conduct

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#50]
The project should include a Code of Conduct and a contact for reporting any breaches of this to the project maintainers. [This version](https://github.com/oneapi-src/oneDNN?tab=coc-ov-file#readme) is widely adopted.

Acceptance Criteria:
- The project has a Code of Conduct and this is listed on the [Community Standards section](https://github.com/oneapi-src/oneDPL/community) of the project
- There is a clear contact method for anyone to report anyone breaking the code of conduct

**Comment by ValentinaKats** [comment]
Added in https://github.com/oneapi-src/oneDPL/pull/1611

**Comment by vbm23** [comment]
Thanks @ValentinaKats and will move to closed status once merged/reviewed by @timmiesmith

**Comment by vbm23** [comment]
https://github.com/oneapi-src/oneDPL/pull/1611 merged
