### ISSUE TITLE
oneDPL getting started guide, features

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#51]
The project documentation should make it straightforward for developers wanting to use multiple vendor targets. There should be clear instructions on both downloading the binaries from the oneAPI Base Toolkit and also how to build from source for different processor targets.

Acceptance Criteria:
- There are clear instructions for developers wanting to use oneDPL with multiple vendors targets, either from binaries or building the source code

**Comment by vbm23** [comment]
@timmiesmith It would be good if you can help provide reference to https://oneapi-src.github.io/oneDPL/introduction/onedpl_gsg.html which may help suffice this ticket, let me know what you think..

**Comment by vbm23** [comment]
@timmiesmith Do we have any progress to report for this ticket, if so then the PR link would be useful.

**Comment by vbm23** [comment]
@timmiesmith mentioned that they have a plan on where the cross-vendor needs to be updated

**Comment by timmiesmith** [comment]
https://github.com/oneapi-src/oneDPL/pull/1951 has been opened to add the instructions on how to use oneDPL on different vendor platforms.

**Comment by timmiesmith** [comment]
https://github.com/oneapi-src/oneDPL/pull/1951 is merged.
