### ISSUE TITLE
oneCCL documented decision making processes

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#53]
Define processes for decision making within the oneCCL project. This should include a RFC process for new design and feature proposals 
(see oneDNN for example - PR tagged RFC that links to the proposal on the GitHub wiki).

Acceptance Criteria:
Decision making process published in the repository and reviewed by the community

**Comment by vbm23** [comment]
@Maria1Petrova Based on this rfc [link](https://github.com/oneapi-src/oneCCL/tree/rfcs), would you consider this ticket as closed?
