### ISSUE TITLE
oneCCL uses consistent versioning

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#55]
oneCCL releases through the open source repository have confusing version numbering, using 2021 in the year 2023. This could cause confusion to users.

**Comment by Maria1Petrova** [comment]
@rodburns  @rozhukov currently we are obliged to follow oneAPI guidelines stating that we can only raise the major version, if we introduce any breaking changes, as a result we are still using 2021. I think this needs to be brought up to a discussion with oneAPI management team.

**Comment by vbm23** [comment]
@Maria1Petrova based on discussion with @rodburns marking this as closed as will be brought up in WIG call as minor versions are being used currently in oneCCL project
