### ISSUE TITLE
oneCCL implements a quality assurance process

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#56]
The [CONTRIBUTING](https://github.com/oneapi-src/oneCCL/blob/master/CONTRIBUTING.md) guide should explain, or link to documentation on how to run the required smoke tests or similar before submitting a PR to the project, and publishing these results with the PR if they are not on a public CI system.

Acceptance Criteria:
- There is clear documentation on how to run any relevant project wide tests required for contributions to the project and this is linked or included in the CONTRIBUTING page

**Comment by vbm23** [comment]
@Maria1Petrova You can refer this ticket https://github.com/uxlfoundation/open-source-working-group/issues/58 for unit test guidelines and commands as a reference

**Comment by vbm23** [comment]
@Maria1Petrova It would be good if the team can aspects on cover functional testing, performance testing, command to run tests & build options
https://github.com/oneapi-src/oneDNN/blob/main/CONTRIBUTING.md#unit-tests

**Comment by maciekpac** [comment]
@vbm23 we have created a brief guide and merged that to opensource.

[the PR](https://github.com/oneapi-src/oneCCL/pull/139)
[the commit](https://github.com/oneapi-src/oneCCL/pull/139/commits/7378fe76f025190c1bc5967af1c9b1b03aee9176)

We decided to start with a short sample showing how to run the default set of tests.

**Comment by vbm23** [comment]
@maciekpac Thanks, that should be all and I will close this ticket
