### ISSUE TITLE
oneDNN document unit test execution

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#58]
Since running the unit tests is part of the PR contribution process it should be clear how to run these. The [CONTRIBUTING](https://github.com/oneapi-src/oneDNN/blob/main/CONTRIBUTING.md#unit-tests) page should link to or list the steps and commands to run them.

Acceptance Criteria:
- Unit tests are suitably documented so that they can be run on all expected target platforms

**Comment by vpirogov** [comment]
Contribution guidelines are updated with information on [how to run unit tests](https://github.com/oneapi-src/oneDNN/blob/main/CONTRIBUTING.md#unit-tests) and links to tests documentation.
