### ISSUE TITLE
oneDPL move license to the expected location

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#60]
GitHub is unable to find the oneDPL license files as they are not in a single file or location for the [community report](https://github.com/oneapi-src/oneDPL/community). Move the licenses to a single file so that they can be linked on the GitHub project page.

Acceptance Criteria:
- A user can link to the license from the GitHub About section

**Comment by timmiesmith** [comment]
https://github.com/oneapi-src/oneDPL/pull/1433 moves the licenses into a properly named directory to satisfy the OSSF scorecard requirements.  Should this be closed in favor of a PR to consolidate into a single file, or is this properly named single location sufficient?

**Comment by rodburns** [comment]
Hi Timmie, go ahead with the changes in 1433, I believe that should satisfy this item.

**Comment by timmiesmith** [comment]
https://github.com/oneapi-src/oneDPL/pull/1478 has been merged moving the license file to the top level directory.
