### ISSUE TITLE
oneMKL Unit test documentation

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#63]
The description of how to run the unit tests assumes knowledge of Google Tests framework. Document how to run the unit tests in the CONTRIBUTOR page or link to the instructions. Include information on running tests on multiple targets.

**Comment by vbm23** [comment]
@mkrainiuk Would it be possible to include details in [oneMKL Contribution Guidelines](https://github.com/oneapi-src/oneMKL/blob/develop/CONTRIBUTING.md) which enlist the steps and commands to run tests on all expected target platforms as GoogleTest is already mentioned under Unit Tests, not sure if you want for "Performance Testing" as well.

You can refer https://github.com/uxlfoundation/open-source-working-group/issues/58 if you like to.

**Comment by vbm23** [comment]
@mkrainiuk Brining this up again for the steps & commands which should complete your existing documentation.

**Comment by mkrainiuk** [comment]
https://github.com/oneapi-src/oneMKL/pull/520 is merged
