### ISSUE TITLE
oneDNN update project pages with UXL identity

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#64]
Update the project pages with the UXL Foundation links, logo and identity.

**Comment by vpirogov** [comment]
Please share more specifics on the expectations:
* Specific links to include.
* Link to logo and where it expected to be used
* Define 'identity'

**Comment by vpirogov** [comment]
oneDNN [README](https://github.com/oneapi-src/oneDNN) page [is updated](https://github.com/oneapi-src/oneDNN/commit/0b24bda7e8de8c6bd65548d25a2619cffa7d7e37).

**Comment by rodburns** [comment]
Thanks for the update Vadim.
