### ISSUE TITLE
oneMKL Update project pages with UXL identity

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#65]
Update the project pages with the UXL Foundation links, logo and identity.

**Comment by rodburns** [comment]
Guidelines:

Update project icon with UXL Foundation logo to replace oneAPI logo unless the project has its own logo

About section:
Link to UXL foundation org https://github.com/uxlfoundation
Include UXL Foundation logo at top of README

The __ project is part of the UXL Foundation (link to http://www.uxlfoundation.org) and is an implementation of the oneAPI specification __ component https://spec.oneapi.io/

New section (in README?) called:
Governance

The __ project is governed by the UXL Foundation and you can get involved in this project in multiple ways. It is possible to join the __ Special Interest Group (SIG) meetings (link to https://github.com/uxlfoundation/foundation) where the groups discuss and demonstrate work using this project. Members can also join the Open Source and Specification Working Group meetings.

You can also join the mailing lists for the UXL Foundation (link to https://lists.uxlfoundation.org/g/main/subgroups) to be informed of when meetings are happening and receive the latest information and discussions.

You can contribute to this project and also contribute to the specification for this project, read the CONTRIBUTING (link to CONTRIBUTING) page for more information.

**Comment by mkrainiuk** [comment]
PR: https://github.com/oneapi-src/oneMKL/pull/479
