### ISSUE TITLE
oneCCL use of Slack channel

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#7]
- Link to the UXL Foundation Slack workspace and channel from the project README
- Assign team member(s) to monitor the Slack channel
- Set up notifications in the oneCCL Slack channel when new RFCs are added to the project repo for community review and comment

Acceptance Criteria:

- Link to Slack available on README
- Named team member(s) monitoring channel
- Notifications appearing on the Slack channel when new RFCs are added to the project

**Comment by vbm23** [comment]
https://github.com/oneapi-src/oneCCL/pull/119 created by @rscohn2 for next steps by @Maria1Petrova

**Comment by vbm23** [comment]
https://github.com/oneapi-src/oneCCL/pull/119 merged and pending Acceptance Criteria is "Named team member(s) monitoring channel" @Maria1Petrova

**Comment by Maria1Petrova** [comment]
Hi, I'll be looking at notifications for now, I've also added Nikita Gusev to the slack channel to help me while we are identifying people to do it

**Comment by vbm23** [comment]
@Maria1Petrova That makes sense and will close this ticket
