### ISSUE TITLE
oneDAL Adopt Vulnerability Policy (Security.md)

### ISSUE THREAD

**Issue by rozhukov** [uxlfoundation/open-source-working-group#71]
1. Adopt Public Security Policy (Security.md file) to UXL.
https://github.com/oneapi-src/oneDAL?tab=security-ov-file
You can use oneDNN as an example: [Security.md](https://github.com/oneapi-src/oneDNN/blob/main/SECURITY.md%5D)
Pay attention to Supported Versions section, it may vary based on your Support policy.
Please add @rozhukov to the reviewers list.

2. Enable Private Vulnerability reporting
GitHub Security tab -> Enable Vulnerability Reporting

![image](https://github.com/uxlfoundation/open-source-working-group/assets/82159361/64910056-3631-4723-80b2-fc007fdcb9e4)

**Comment by rozhukov** [comment]
Adopt Public Security Policy (Security.md) to UXL.
You can use oneDNN as an example: [Security.md](https://github.com/oneapi-src/oneDNN/blob/main/SECURITY.md%5D)

Pay attention to Supported Versions section, it may vary based on your Support policy.

**Comment by rozhukov** [comment]
duplicate

**Comment by rozhukov** [comment]
duplicate

**Comment by rozhukov** [comment]
Waiting for minor fixes

**Comment by napetrov** [comment]
https://github.com/oneapi-src/oneDAL/pull/2798

**Comment by rozhukov** [comment]
Submitted a few minor issues here: https://github.com/oneapi-src/oneDAL/pull/2798#issuecomment-2188347195
Thus reopening.

**Comment by rozhukov** [comment]
All is good new. Thank you team!
