### ISSUE TITLE
oneMKL Adopt Vulnerability Policy (Security.md)

### ISSUE THREAD

**Issue by rozhukov** [uxlfoundation/open-source-working-group#72]
1. Adopt Public Security Policy (Security.md file) to UXL.
(!) There is no Security.md file for oneMKL at all: https://github.com/oneapi-src/oneMKL?tab=security-ov-file
You can use oneDNN as an example: [Security.md](https://github.com/oneapi-src/oneDNN/blob/main/SECURITY.md%5D)
Pay attention to Supported Versions section, it may vary based on your Support policy.
Please add @rozhukov to the reviewers list.

3. Enable Private Vulnerability reporting
GitHub Security tab -> Enable Vulnerability Reporting

![image](https://github.com/uxlfoundation/open-source-working-group/assets/82159361/64910056-3631-4723-80b2-fc007fdcb9e4)

**Comment by vmalia** [comment]
@rozhukov you can assign this one to me.

**Comment by rozhukov** [comment]
@vmalia I thought it's WIP already. Please let me know once done. Thx.

**Comment by vmalia** [comment]
@rozhukov 
I have maintainer permissions for the oneMKL project but cannot see the "Private Vulnerability Reporting" option.

![Image](https://github.com/uxlfoundation/open-source-working-group/assets/48330936/1efe80dc-b6ba-4580-9856-3be07b3ae774)

Verified the same with another maintainer. Is there something else that needs to be configured for this option to appear?

**Comment by rozhukov** [comment]
> @rozhukov I have maintainer permissions for the oneMKL project but cannot see the "Private Vulnerability Reporting" option.
> 
> ![Image](https://private-user-images.githubusercontent.com/48330936/334492920-1efe80dc-b6ba-4580-9856-3be07b3ae774.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTUxNDMsIm5iZiI6MTcxNjkxNDg0MywicGF0aCI6Ii80ODMzMDkzNi8zMzQ0OTI5MjAtMWVmZTgwZGMtYjZiYS00NTgwLTk4NTYtM2JlMDdiM2FlNzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDE2NDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZjExYTQyYjIyOWRkM2JhNDU4MGQ5NDYyOTM1Yjg2ODUxZjg2ZWMwMGNkNTlmM2EwZjAyZDYzMjY5Zjg4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zuzMzTbWFopOQDTQb2nkE2GJwciRqHF2r-9UQdidxAs)
> 
> Verified the same with another maintainer. Is there something else that needs to be configured for this option to appear?

Yes, you should be either owner or admin. With our internal Intel guidance I advised it many times to get added to owner-* GitHub teams. I think it'd make sense to re-evaluate access permissions and roles ones migration to UXL-owned org is done.
