### ISSUE TITLE
oneCCL Adopt Vulnerability Policy (Security.md)

### ISSUE THREAD

**Issue by rozhukov** [uxlfoundation/open-source-working-group#74]
1. Adopt Public Security Policy (Security.md file) to UXL.
https://github.com/oneapi-src/oneCCL?tab=security-ov-file
You can use oneDNN as an example: [Security.md](https://github.com/oneapi-src/oneDNN/blob/main/SECURITY.md%5D)
Pay attention to Supported Versions section, it may vary based on your Support policy.
Please add @rozhukov to the reviewers list.

2. Enable Private Vulnerability reporting
GitHub Security tab -> Enable Vulnerability Reporting

![image](https://github.com/uxlfoundation/open-source-working-group/assets/82159361/64910056-3631-4723-80b2-fc007fdcb9e4)

**Comment by Maria1Petrova** [comment]
https://github.com/oneapi-src/oneCCL/blob/master/SECURITY.md
