### ISSUE TITLE
Enable Open SSF Scorecard GitHub Badge

### ISSUE THREAD

**Issue by rozhukov** [uxlfoundation/open-source-working-group#79]
For those repos have decent score (7 or above) it's recommended to enable a badge for your repo:
https://github.com/ossf/scorecard?tab=readme-ov-file#scorecard-badges

Example: https://github.com/OpenVisualCloud/Media-Transport-Library

![Image](https://github.com/uxlfoundation/open-source-working-group/assets/82159361/7e20ba10-8228-4540-a99b-2f226c157fa1)

**Comment by vpirogov** [comment]
Enabled OSSF scorecard checklist scans and added the badge for oneDNN

![image](https://github.com/uxlfoundation/open-source-working-group/assets/19210288/ec6717d9-30e2-4297-a3c9-7463bf707a5e)

**Comment by rozhukov** [comment]
Fantastic! Thank you Vadim for that and also for keeping the 8.0 score high bar.
