### ISSUE TITLE
oneMKL identified lead maintainers

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#8]
- Publish the names of the lead maintainers and reviewers for contributions to the project.
- Identified way to contact lead maintainers of the project published on the project README

Acceptance Criteria:
- The README or CONTRIBUTOR file lists the lead maintainers
- The README or CONTRIBUTOR file lists how to contact the project maintainers

**Comment by vbm23** [comment]
Named team member(s) monitoring channel required based on #4

**Comment by mkrainiuk** [comment]
The list of Intel maintainers was defined, we are working on creating new github teams that will include all maintainers and also reps for each domain: 
<img src="https://github.com/uxlfoundation/open-source-working-group/assets/28574953/2509e32e-2c87-41f2-bc78-1b0e827dd8c4" width=300>

**Comment by vbm23** [comment]
@mkrainiuk Reopening this issue as links in Readme file not reachable to external users, hence can not contact maintainers

**Comment by mkrainiuk** [comment]
Links were fixed in https://github.com/oneapi-src/oneMKL/pull/520
