### ISSUE TITLE
oneDNN identified lead maintainers

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#9]
- Publish the names of the lead maintainers and reviewers for contributions to the project.
- Identified way to contact lead maintainers of the project published on the project README

Acceptance Criteria:
- The README or CONTRIBUTOR file lists the lead maintainers
- The README or CONTRIBUTOR file lists how to contact the project maintainers

**Comment by vpirogov** [comment]
Published list of maintainers in [MAINTAINERS.md](https://github.com/oneapi-src/oneDNN/blob/main/MAINTAINERS.md).
