### ISSUE TITLE
oneTBB Add templates to issue tracker

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#98]
Implement issue templates for the issue tracker on the GitHub project.
The oneMKL project does this https://github.com/oneapi-src/oneMKL/issues/new/choose and can be used to help make the templates.

Acceptance Criteria:

Templates have been added to the project

**Comment by vbm23** [comment]
@pavelkumbrasev This ticket is due for Q2, perhaps you can help to prioritize this before June 28th timeline if possible.

**Comment by pavelkumbrasev** [comment]
https://github.com/oneapi-src/oneTBB/pull/1400

**Comment by vbm23** [comment]
Issue template introduced through MR https://github.com/oneapi-src/oneTBB/pull/1400
