### ISSUE TITLE
oneTBB use of Slack channel

### ISSUE THREAD

**Issue by rodburns** [uxlfoundation/open-source-working-group#99]
- Link to the UXL Foundation Slack workspace and channel from the project README
- Assign team member(s) to monitor the Slack channel
- Set up notifications in the oneTBB Slack channel when new RFCs are added to the project repo for community review and comment

Acceptance Criteria:

- Link to Slack available on README
- Named team member(s) monitoring channel
- Notifications appearing on the Slack channel when new RFCs are added to the project

**Comment by pavelkumbrasev** [comment]
Hi @rodburns and @vbm23, we have discussed the applicability of Slack channel to our project within the team and come up to the conclusion that we would prefer to keep all the customers communications in our public repo.
With the Slack channel we will introduce new place where oneTBB users can ask their questions that we should monitor. That makes it more complicated for us to maintain. We have not the best experience with [Intel oneTBB forum](https://community.intel.com/t5/Intel-oneAPI-Threading-Building/bd-p/oneapi-threading-building-blocks)  where questions/discussions can be unattended for a long time.
So we would like to use: GitHub Issues (for contributions + small questions) and GitHub Discussions (for bigger questions and development decisions) and close oneTBB slack channel.

What do you think?

**Comment by rodburns** [comment]
Hi Pavel, if you have existing channels for communication that is fine, we don't have to have the Slack channel as well.
I agree with your approach, can you just make sure these channels are clearly documented in the README file for the project? At the moment the discussions are linked, but perhaps it could be clearer what discussions are had there.

**Comment by rodburns** [comment]
Another note, there are 94 people in the oneTBB Slack channel so it would be good if somoene could go in and explain the alternative channel to monitory for oneTBB activity.

**Comment by pavelkumbrasev** [comment]
> Discussions are linked, but perhaps it could be clearer what discussions are had there.

> Another note, there are 94 people in the oneTBB Slack channel so it would be good if somoene could go in and explain the alternative channel to monitory for oneTBB activity.

Sounds good will work on this.

**Comment by vbm23** [comment]
@pavelkumbrasev Once you have covered the relevant actions such as capturing the details in the readme file if not already towards GitHub Issues and GitHub Discussions, do help share the PR, so we can then consider this ticket as done in contrast to the acceptance criteria stated above, else feel free to close this ticket.
